### ISSUE TITLE
manage-other-grids doesn't work

### ISSUE THREAD

**Issue by hades200082** [JakenVeina/SpaceEngineersScripts#1]
Programmable block is on a rotor (large grid rotor with small head - to save space on large grid ship)

Custom data is:

```
block-tag:Door
manage-other-grids
```

Door name is: `[Door]:manage`

Have recompiled the script, run it with "run" as the argument, etc. Programmable block states "Discovered 0 doors for management".

If I change the PB custom data to:

```
block-tag:Door
auto-manage-other-grids
```

Then it finds the tagged door AND all of my hangar doors too and closes everything.

**Comment by JakenVeina** [comment]
Roger. That definitely sounds like a bug. I'll see if I can reproduce tomorrow.
